name: stored_notifier
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5

flutter:
